import bpy

def is_valid_rig(rigObject):
    if (rigObject.type == "ARMATURE" and
        (rigObject.library == None or rigObject.library == "") and
        rigObject in bpy.context.scene.objects.values()):
        return True
    return False

def is_rigify_rig(rigObject):
    # rig_id is a custom property generated by rigify, use it to detect rigify rigs.
    return rigObject.data.get("rig_id") != None

def replace_prefix(string, oldprefix, newprefix):
    if string.startswith(oldprefix):
        string = string[len(oldprefix):]
    else:
        raise Exception(f'String "{string}" does not start with prefix "{oldprefix}"')
    return newprefix + string

def replace_suffix(string, oldsuffix, newsuffix):
    if string.endswith(oldsuffix):
        string = string[:-len(oldsuffix)]
    else:
        raise Exception(f'String "{string}" does not end with suffix "{oldsuffix}"')
    return string + newsuffix
